CREATE TABLE "FUNCIONARIO" (
"INTCODIGO" NUMBER NOT NULL ENABLE,
"STRNOME" VARCHAR2(400) NOT NULL ENABLE,
"DTMNASCIMENTO" DATE,
"STRRG" VARCHAR2(20),
"STRCPF" VARCHAR2(20),
"INTSEXO" NUMBER(1),
"INTESTRAGEIRO" NUMBER(1),
"STRESCOLARIDADE" VARCHAR2(300),
"STRESTADO_CIVIL" VARCHAR2(200),
"INTATIVO" NUMBER(1) NOT NULL ENABLE,
"STRTELEFONE" VARCHAR2(50),
"STREMAIL" VARCHAR2(100),
"STRAREAS_INTERESSE" VARCHAR2(1000),
"IMGFOTO" BLOB,
"FILENAME" VARCHAR2(200),
"STROBSERVACAO" VARCHAR2(1000),
CONSTRAINT "FUNCIONARIO_PK" PRIMARY KEY ("INTCODIGO") ENABLE
);
/
CREATE SEQUENCE "FUNCIONARIO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
/
CREATE trigger "BI_FUNCIONARIO"
before insert on "FUNCIONARIO"
for each row
begin
if :NEW."INTCODIGO" is null then
select "FUNCIONARIO_SEQ".nextval into :NEW."INTCODIGO" from sys.dual;
end if;
end;
